services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: always
    
  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
  
  wishlist:
    build: .
    ports:
      - "50051:50051"
    depends_on:
        postgres:
          condition: service_healthy